### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Nandulucky** [shiki/STableViewController#2]
Hi,

When im open the code in XCode6.3.1 I got an Issue in STableViewController.
Please find the Below Issue.

ld: -pie can only be used when targeting iOS 4.2 or later
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by shiki** [comment]
@Nandulucky This library has been deprecated in favor of [SKStatefulTableViewController](http://github.com/shiki/SKStatefulTableViewController)
